# Generated by Django 5.1.1 on 2024-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="closed",
            field=models.BooleanField(null=True, verbose_name="Is the option closed"),
        ),
        migrations.AlterField(
            model_name="option",
            name="purchase_price",
            field=models.FloatField(null=True, verbose_name="Price Purchased"),
        ),
        migrations.AlterField(
            model_name="option",
            name="when_closed",
            field=models.DateField(
                null=True, verbose_name="When was this option closed"
            ),
        ),
    ]
