# Generated by Django 5.1.1 on 2024-09-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="live_pl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Live Profit/Loss on this option",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="num_open",
            field=models.IntegerField(default=1, verbose_name="Owned Securities"),
        ),
        migrations.AlterField(
            model_name="option",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="investments.ticker"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="num_open",
            field=models.IntegerField(default=1, verbose_name="Owned Securities"),
        ),
        migrations.AlterField(
            model_name="share",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="investments.ticker"
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Full Name of Stock"
            ),
        ),
    ]
