# Generated by Django 5.1.1 on 2024-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "investments",
            "0002_alter_option_closed_alter_option_purchase_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="closed",
        ),
        migrations.AddField(
            model_name="option",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Is the option active"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="purchase_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price Purchased"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="when_closed",
            field=models.DateField(
                blank=True, null=True, verbose_name="When was this option closed"
            ),
        ),
    ]
