# Generated by Django 5.1.1 on 2024-09-08 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0003_remove_option_closed_option_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="option",
            name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="option",
            name="when_closed",
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_quantity",
                    models.IntegerField(
                        default=1, verbose_name="How many base options were purchased"
                    ),
                ),
                (
                    "num_legs",
                    models.IntegerField(
                        default=1, verbose_name="How many legs does this position have?"
                    ),
                ),
                (
                    "purchase_price",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Avg Price Purchased"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is the option active"
                    ),
                ),
                (
                    "when_closed",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="When was this option closed",
                    ),
                ),
                (
                    "profit",
                    models.FloatField(
                        verbose_name="When closed, what was the profit made on this position"
                    ),
                ),
                (
                    "base_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investments.option",
                    ),
                ),
            ],
        ),
    ]
