# Generated by Django 5.1.1 on 2024-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0003_alter_ticker_nasdaq_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(
                default=-1,
                verbose_name="How many shares/options were purchased or sold",
            ),
            preserve_default=False,
        ),
    ]
