# Generated by Django 5.1.1 on 2024-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0004_transaction_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="live_pl",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Live Profit/Loss on this option"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="profit_loss",
            field=models.FloatField(
                default=0, verbose_name="Total Profit/Loss on this option"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="average_price",
            field=models.FloatField(verbose_name="Average Price of Purchase"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.FloatField(verbose_name="What did this cost per security"),
        ),
    ]
