# Generated by Django 5.1.1 on 2024-09-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "investments",
            "0004_remove_option_is_active_remove_option_purchase_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="profit",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="When closed, what was the profit made on this position",
            ),
        ),
    ]
