# Generated by Django 5.1.1 on 2024-09-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0005_alter_option_live_pl_alter_option_profit_loss_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="profit_loss",
        ),
        migrations.AddField(
            model_name="option",
            name="cost_basis",
            field=models.FloatField(
                default=0, verbose_name="Cost Basis of this option"
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="current_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Value of this option"
            ),
        ),
    ]
