# Generated by Django 5.1.1 on 2024-09-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0005_alter_position_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="base_quantity",
            field=models.IntegerField(
                default=-1, verbose_name="How many base options were purchased"
            ),
        ),
    ]
