# Generated by Django 5.1.1 on 2024-09-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0006_remove_option_profit_loss_option_cost_basis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="num_open",
            field=models.FloatField(default=1, verbose_name="Owned Securities"),
        ),
        migrations.AlterField(
            model_name="share",
            name="num_open",
            field=models.FloatField(default=1, verbose_name="Owned Securities"),
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_open",
                    models.FloatField(default=1, verbose_name="Owned Securities"),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        default="FXAIX",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investments.ticker",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
