# Generated by Django 5.1.1 on 2024-09-10 04:52

import investments.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0007_alter_option_num_open_alter_share_num_open_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="type",
            field=models.CharField(
                choices=[
                    ("sto", "Stock"),
                    ("etf", "ETF"),
                    ("mm", "Money Market"),
                    ("mf", "Mutual Fund"),
                ],
                default="sto",
                max_length=3,
                validators=[investments.models.validate_ticker_type],
            ),
            preserve_default=False,
        ),
    ]
