# Generated by Django 5.1.1 on 2024-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0008_ticker_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="live_pl",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Live Profit/Loss on this option",
            ),
        ),
    ]
