# Generated by Django 5.1.1 on 2024-09-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0009_alter_option_live_pl"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="cost_basis",
            field=models.FloatField(default=0, verbose_name="Cost Basis Per Share"),
        ),
        migrations.AddField(
            model_name="share",
            name="current_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Current Value of this stock"
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="live_pl",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Live Profit/Loss on these shares",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="cost_basis",
            field=models.FloatField(default=0, verbose_name="Cost Basis Per Option"),
        ),
    ]
