# Generated by Django 5.1.1 on 2024-09-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "investments",
            "0010_share_cost_basis_share_current_value_share_live_pl_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(verbose_name="What was the portfolio valued at?"),
                ),
                ("date", models.DateField(verbose_name="When was this value accrued?")),
            ],
        ),
        migrations.RemoveField(
            model_name="share",
            name="average_price",
        ),
        migrations.AlterField(
            model_name="option",
            name="current_value",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Current Value of this option",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="current_value",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Current Value of this stock",
            ),
        ),
    ]
