# Generated by Django 5.1.1 on 2024-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0011_portfoliotracker_remove_share_average_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cash",
            name="num_open",
        ),
        migrations.AddField(
            model_name="cash",
            name="description",
            field=models.CharField(
                choices=[("d", "Deposit"), ("i", "Interest"), ("t", "Transaction")],
                default="Deposit",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="option",
            name="cost_basis",
            field=models.FloatField(default=0, verbose_name="Cost Basis Per Share"),
        ),
        migrations.AlterField(
            model_name="option",
            name="current_value",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Current Value of this stock",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="live_pl",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Live Profit/Loss on these shares",
            ),
        ),
    ]
