# Generated by Django 5.1.1 on 2024-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0012_remove_cash_num_open_cash_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="num_open",
            field=models.FloatField(default=1, verbose_name="Owned Securities"),
        ),
    ]
