# Generated by Django 5.1.1 on 2024-09-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0013_cash_num_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="description",
            field=models.CharField(
                choices=[("d", "Deposit"), ("i", "Interest")], default="d", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="num_open",
            field=models.FloatField(default=1, verbose_name="Owned Cash"),
        ),
        migrations.AlterField(
            model_name="option",
            name="cost_basis",
            field=models.FloatField(default=0, verbose_name="Cost Basis Per Security"),
        ),
        migrations.AlterField(
            model_name="option",
            name="current_value",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Current Value of this Security",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="live_pl",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Live Profit/Loss on These Securities",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="cost_basis",
            field=models.FloatField(default=0, verbose_name="Cost Basis Per Security"),
        ),
        migrations.AlterField(
            model_name="share",
            name="current_value",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Current Value of this Security",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="live_pl",
            field=models.FloatField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Live Profit/Loss on These Securities",
            ),
        ),
    ]
