# Generated by Django 5.1.1 on 2024-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0014_alter_cash_description_alter_cash_num_open_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="value",
            field=models.FloatField(
                default=0, verbose_name="Total value of the transaction"
            ),
            preserve_default=False,
        ),
    ]
