# Generated by Django 5.1.1 on 2024-09-17 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0015_transaction_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cash",
            name="ticker",
        ),
    ]
