# Generated by Django 5.1.1 on 2024-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0016_remove_cash_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="description",
            field=models.CharField(
                choices=[("d", "Deposit"), ("i", "Interest"), ("m", "Main")],
                default="d",
                max_length=1,
            ),
        ),
    ]
